// Generated by gencpp from file gp_planner/BoundingBoxWithTime.msg
// DO NOT EDIT!


#ifndef GP_PLANNER_MESSAGE_BOUNDINGBOXWITHTIME_H
#define GP_PLANNER_MESSAGE_BOUNDINGBOXWITHTIME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gp_planner
{
template <class ContainerAllocator>
struct BoundingBoxWithTime_
{
  typedef BoundingBoxWithTime_<ContainerAllocator> Type;

  BoundingBoxWithTime_()
    : header()
    , left_x(0.0)
    , right_x(0.0)
    , up_y(0.0)
    , down_y(0.0)  {
    }
  BoundingBoxWithTime_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_x(0.0)
    , right_x(0.0)
    , up_y(0.0)
    , down_y(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _left_x_type;
  _left_x_type left_x;

   typedef float _right_x_type;
  _right_x_type right_x;

   typedef float _up_y_type;
  _up_y_type up_y;

   typedef float _down_y_type;
  _down_y_type down_y;





  typedef boost::shared_ptr< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBoxWithTime_

typedef ::gp_planner::BoundingBoxWithTime_<std::allocator<void> > BoundingBoxWithTime;

typedef boost::shared_ptr< ::gp_planner::BoundingBoxWithTime > BoundingBoxWithTimePtr;
typedef boost::shared_ptr< ::gp_planner::BoundingBoxWithTime const> BoundingBoxWithTimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gp_planner::BoundingBoxWithTime_<ContainerAllocator1> & lhs, const ::gp_planner::BoundingBoxWithTime_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_x == rhs.left_x &&
    lhs.right_x == rhs.right_x &&
    lhs.up_y == rhs.up_y &&
    lhs.down_y == rhs.down_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gp_planner::BoundingBoxWithTime_<ContainerAllocator1> & lhs, const ::gp_planner::BoundingBoxWithTime_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gp_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f7bcaf4671d6882f7146f67396528cb";
  }

  static const char* value(const ::gp_planner::BoundingBoxWithTime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f7bcaf4671d6882ULL;
  static const uint64_t static_value2 = 0xf7146f67396528cbULL;
};

template<class ContainerAllocator>
struct DataType< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gp_planner/BoundingBoxWithTime";
  }

  static const char* value(const ::gp_planner::BoundingBoxWithTime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 文件名：BoundingBoxWithTime.msg\n"
"std_msgs/Header header\n"
"float32 left_x   # 左边界的x坐标\n"
"float32 right_x  # 右边界的x坐标\n"
"float32 up_y     # 上边界的y坐标\n"
"float32 down_y   # 下边界的y坐标\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gp_planner::BoundingBoxWithTime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_x);
      stream.next(m.right_x);
      stream.next(m.up_y);
      stream.next(m.down_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBoxWithTime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gp_planner::BoundingBoxWithTime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gp_planner::BoundingBoxWithTime_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_x: ";
    Printer<float>::stream(s, indent + "  ", v.left_x);
    s << indent << "right_x: ";
    Printer<float>::stream(s, indent + "  ", v.right_x);
    s << indent << "up_y: ";
    Printer<float>::stream(s, indent + "  ", v.up_y);
    s << indent << "down_y: ";
    Printer<float>::stream(s, indent + "  ", v.down_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GP_PLANNER_MESSAGE_BOUNDINGBOXWITHTIME_H
