real_robot: false
robot:
  DOF: 6
  arm_base: {orientation: [0, 0, 0, 1], position: [0, 0, 0]}
  DH:
    alpha: [1.5708, 0.0, 0.0, 1.5708, -1.5708, 0.0]
    a: [0.0, -0.427, -0.357, 0.0, 0.0, 0.0]
    d: [0.147, 0.0, 0.0, 0.141, 0.116, 0.105]
    theta: [0.0, -1.5708, 0.0, -1.5708, 0.0, 0.0]
  spheres: 
    js: [0,0,1,1,1,1,1,1,2,2,2,3,4,5,5]
    xs: [0,0,0,0.105,0.210,0.315,0.420,0,0.11,0.22,0,0,0,0,0]
    ys: [-0.1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    zs: [0,0,0.1,0.1,0.1,0.1,0.1,0,0,0,0,0,0,0,0.1]
    rs: [0.08,0.08,0.06,0.06,0.06,0.06,0.06,0.08,0.06,0.06,0.08,0.07,0.06,0.06,0.06]
  arm_joint_names: [joint1, joint2, joint3, joint4, joint5, joint6]
  arm_state_topic: /joint_states
  trajectory_control_topic: /arm_joint_controller/follow_joint_trajectory
  est_traj_pub_topic: /gpmp2_planner/est_traj
  plan_traj_pub_topic: /gpmp2_planner/plan_traj

global_planner:
  step_rate: 0.03
  fai_rate: 1.01
  MAX_TREE_NUM: 2000

settings:
  sdf_file: sdf/obs_test_one_box.bin
  frequency: 2
  ref_inter_num: 4
  total_time: 1.5
  total_step: 10
  obs_check_inter: 5
  control_inter: 5
  cost_sigma: 0.02
  epsilon: 0.1
  fix_pose_sigma: 0.0001
  fix_vel_sigma: 0.0001
  Qc: 1.0
  opt_type: LM
  flag_pos_limit: true
  flag_vel_limit: true
  joint_pos_limits_up: 3.14
  joint_pos_limits_down: -3.14
  max_vel: 1.0
  pos_limit_sigma: 0.0001
  vel_limit_sigma: 0.0001
  goal_tolerance: 0.05
  decay_factor: 0.5
  map_update_frenquency: 5

sdf:
  static_file: /home/roboert/MP_WS/src/gp_planner/sdf_data/sdf_data_static_py.txt
  dynamic_file: /home/roboert/MP_WS/src/gp_planner/sdf_data/sdf_data_dynamic_py.txt
  origin_x: -1
  origin_y: -1
  origin_z: -0.35
  cell_size: 0.05
  rows: 40
  cols: 40
  z: 30

